services:
  - type: web
    plan: free
    name: artleechrenderjmdkh
    env: docker
    #buildCommand: pip install -U -r requirements.txt
    #startCommand: gunicorn app:app & python3 -m Zaid
    repo: https://github.com/assc0d3r/ARTLEECHRENDERBYPASSS      
    branch: main
    envVars:
      - key: DATABASE_URL 
        sync: false
      - key: TELEGRAM_HASH 
        sync: false
      - key: TELEGRAM_API 
        sync: false
      - key: OWNER_ID
        sync: false
      - key: BOT_TOKEN
        sync: false    
    autoDeploy: false
